<?php 
declare(strict_types=1);
# Generated by the Minichan compiler. DO NOT EDIT!
# source: proto/login-register.proto

namespace PHP\LoginRegister;


interface LoginRegisterServiceInterface extends \Minichan\Grpc\ServiceInterface
{
    public const NAME = "/PHP.LoginRegister.LoginRegisterService";

    /**
    * @param \Minichan\Grpc\ContextInterface $ctx
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function AddUser(\Minichan\Grpc\ContextInterface $ctx, Users $request): Response;

    /**
    * @param \Minichan\Grpc\ContextInterface $ctx
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function LoginUser(\Minichan\Grpc\ContextInterface $ctx, Users $request): Response;
}
