<?php declare(strict_types=1);
# Generated by the Minichan compiler. DO NOT EDIT!
# source: proto/login-register.proto

namespace PHP\LoginRegister;


class LoginRegisterServiceClient extends \Minichan\Grpc\BaseStub
{


	/**
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function AddUser(Users $request, $metadata = []): Response {
    	return $this->_serverStreamRequest('/PHP.LoginRegister.LoginRegisterService/AddUser',
        $request,
        ['\PHP\LoginRegister\Response', 'decode'],
        $metadata); 
    }

	public function getNext(): object {
	    return $this->_getData();
	}



	/**
    * @param Users $request
    * @return Response
    *
    * @throws \Minichan\Exception\InvokeException
    */
    public function LoginUser(Users $request, $metadata = []): Response {
    	return $this->_serverStreamRequest('/PHP.LoginRegister.LoginRegisterService/LoginUser',
        $request,
        ['\PHP\LoginRegister\Response', 'decode'],
        $metadata); 
    }
}
