<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/login-register.proto

namespace PHP\LoginRegister;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PHP.LoginRegister.Users</code>
 */
class Users extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     */
    protected $userId = 0;
    /**
     * Generated from protobuf field <code>int32 uniqueId = 2;</code>
     */
    protected $uniqueId = 0;
    /**
     * Generated from protobuf field <code>string fname = 3;</code>
     */
    protected $fname = '';
    /**
     * Generated from protobuf field <code>string lname = 4;</code>
     */
    protected $lname = '';
    /**
     * Generated from protobuf field <code>string email = 5;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>string password = 6;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string img = 7;</code>
     */
    protected $img = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $userId
     *     @type int $uniqueId
     *     @type string $fname
     *     @type string $lname
     *     @type string $email
     *     @type string $password
     *     @type string $img
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\LoginRegister::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>int32 userId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkInt32($var);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 uniqueId = 2;</code>
     * @return int
     */
    public function getUniqueId()
    {
        return $this->uniqueId;
    }

    /**
     * Generated from protobuf field <code>int32 uniqueId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUniqueId($var)
    {
        GPBUtil::checkInt32($var);
        $this->uniqueId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fname = 3;</code>
     * @return string
     */
    public function getFname()
    {
        return $this->fname;
    }

    /**
     * Generated from protobuf field <code>string fname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFname($var)
    {
        GPBUtil::checkString($var, True);
        $this->fname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lname = 4;</code>
     * @return string
     */
    public function getLname()
    {
        return $this->lname;
    }

    /**
     * Generated from protobuf field <code>string lname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLname($var)
    {
        GPBUtil::checkString($var, True);
        $this->lname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 5;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 6;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string img = 7;</code>
     * @return string
     */
    public function getImg()
    {
        return $this->img;
    }

    /**
     * Generated from protobuf field <code>string img = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setImg($var)
    {
        GPBUtil::checkString($var, True);
        $this->img = $var;

        return $this;
    }

}

